<%@ Page Language="VB" AutoEventWireup="true" CodeFile="PortalNavigator.aspx.vb" Inherits="_CMS_PortalNavigator" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>Portal Navigator</title>
    <link href="/_CMS/styles/style.css" rel="stylesheet" type="text/css" />
    <style type="text/css">
        body
        {
            background: #f0f0f0;
        }
        a:hover
        {
            text-decoration: none;
        }
    </style>
    <!--
    <script type="text/javascript">
        if (top.location.pathname.toLowerCase() == "/_cms/portalnavigator.aspx")
        {
            top.location.href = "Master.aspx";
        }
    </script>
    -->
</head>
<body>
    <form id="frmMain" runat="server">
        <div style="padding: 3px; font-size: 11px; color: #0066ff; padding-bottom: 8px">
            <asp:LinkButton ID="cmdSync" runat="server" Text="Synchronize" OnClick="cmdSync_Click" Style="color: #0066ff; text-decoration: underline" />&nbsp;|&nbsp;<asp:LoginStatus Visible="true"
                    ID="LoginStatus1" runat="server" Style="color: #0066ff; text-decoration: underline" LogoutAction="RedirectToLoginPage" />
        </div>
        <asp:TreeView ID="t" runat="server" Target="_f" AutoGenerateDataBindings="False"
            CollapseImageUrl="i/tv/c.gif" ExpandImageUrl="i/tv/e.gif" LineImagesFolder="i/tv/l"
            EnableTheming="True" NodeWrap="False" NoExpandImageUrl="i/tv/l/ne.gif" EnableClientScript="False">
            <ParentNodeStyle Font-Bold="True" ImageUrl="i/tv/f.gif" />
            <HoverNodeStyle Font-Underline="False" Font-Overline="False" ForeColor="DarkOrange" />
            <SelectedNodeStyle BackColor="#B5B5B5" Font-Underline="False" />
            <NodeStyle Font-Names="Tahoma" Font-Size="8pt" ForeColor="#3366CC" HorizontalPadding="5px"
                VerticalPadding="2px" />
            <RootNodeStyle Font-Bold="True" Font-Size="10pt" ImageUrl="i/tv/w.gif" />
            <LeafNodeStyle Font-Bold="False" ImageUrl="i/tv/t.gif" />
        </asp:TreeView>
    </form>
</body>
</html>
